plugins {
  alias(libs.plugins.android.library)
  alias(libs.plugins.kotlin.android)
  alias(libs.plugins.kotlin.serialization)
  alias(libs.plugins.ksp)
  alias(libs.plugins.hilt)
}

android {
  namespace "dev.antigravity.classevivaexpressive.core.database"
  compileSdk 36

  defaultConfig {
    minSdk 26
    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  sourceSets {
    androidTest.assets.srcDirs += files("$projectDir/schemas")
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = "17"
  }
}

ksp {
  arg("room.schemaLocation", "$projectDir/schemas")
}

dependencies {
  implementation project(":core:core-domain")
  implementation libs.androidx.core.ktx
  implementation libs.room.runtime
  implementation libs.room.ktx
  implementation libs.hilt.android
  implementation libs.serialization.json

  ksp libs.room.compiler
  ksp libs.hilt.compiler
  kspAndroidTest libs.room.compiler

  testImplementation libs.junit4
  androidTestImplementation libs.androidx.test.ext.junit
  androidTestImplementation libs.androidx.test.runner
  androidTestImplementation libs.room.testing
  androidTestImplementation libs.kotlinx.coroutines.test
  androidTestImplementation libs.turbine
}
